### ISSUE TITLE
TODO: Log waypoints in tele-op

### ISSUE THREAD

**Issue by ryanlarkin** [FRC2994/Autonomous#11]
This would be done using the format used to parse auto.log in autonomous.

**Comment by ryanlarkin** [comment]
@georgetzavelas and @D3ZOMBKEELA got PID working.  I now have to put it into our program.

**Comment by eandr127** [comment]
Will you be in today or should I finish this on my own?

**Comment by ryanlarkin** [comment]
The robot parts are in, so we won't be able to use the robot tomorrow.

**Comment by JackMc** [comment]
We can make a test harness. We got this :)

**Comment by ryanlarkin** [comment]
So we do have kitbot.  The logging seems to work, but I am having problems with the encoder PIDs not stopping.

**Comment by ryanlarkin** [comment]
This was my output from logging:

-378.6706379296978, 6.822754131992602
-0.17036232584626987, 1.2216708082909538
3.208259856052166, -1.039072131684389
401.5889565362089, -7.271849476036369

It gets stuck on the second line.

**Comment by JackMc** [comment]
Check the directions of the encoders vs. the speeds and the epsilon? In
addition see if you can make it work with dead reckoning (our basic method
with the while loop).

**Comment by JackMc** [comment]
Hm. So it dies on the move backwards?

**Comment by ryanlarkin** [comment]
No, it was moving forward, and turning 0.17 degrees.

**Comment by JackMc** [comment]
I will be there soon

**Comment by ryanlarkin** [comment]
I have finished the logging and pushed it to my fork, but I still want to finish the work on the new format (#29).

**Comment by ryanlarkin** [comment]
Fixed in PR #30

**Comment by ryanlarkin** [comment]
Merged PR #30
