### ISSUE TITLE
Possible Minor Addition: Load Gyro Init from File

### ISSUE THREAD

**Issue by ryanlarkin** [FRC2994/Autonomous#26]
I was wondering whether it would be possible to, instead of initialising the gyro on the spot, load it from a file that is created in test. (Although there would have to be a switch between this and the encoder calibration)

**Comment by JackMc** [comment]
If you're referring to Java serialization, I don't think that'd work. There
are necessary steps that impact hardware and other classes in the
constructor.

**Comment by ryanlarkin** [comment]
I am going to look at the source to see if this is possible, but maybe find a variable that is changed that can be loaded from a file.

**Comment by ryanlarkin** [comment]
Unless there are methods for accessing a lot of the variables inside Gyro, then it would probably just be easier to initialize it in the constructor.

**Comment by JackMc** [comment]
Sounds good.

**Comment by ryanlarkin** [comment]
Now initializes in constructor (#27)

**Comment by JackMc** [comment]
Good job!
