### ISSUE TITLE
Minor TODO: Create gh-pages branch to hold javadocs

### ISSUE THREAD

**Issue by ryanlarkin** [FRC2994/Autonomous#9]
I have a working branch on my fork that can be pulled once the branch is created.

**Comment by JackMc** [comment]
Good job! I won't be in today cause I'm sick :(

**Comment by ryanlarkin** [comment]
Thank you.  Hope you feel better.

**Comment by ryanlarkin** [comment]
Done.  URL is http://frc2994.github.io/Autonomous/
